import json
players=[]
def add(name,pos,nat,flag,team,code,diff,aliases=None):
    players.append(dict(name=name,position=pos,nationality=nat,flag=flag,team=team,teamCode=code,difficulty=diff,aliases=aliases or [name]))
# LaLiga
rows=[
('Lamine Yamal','ED','España','🇪🇸','FC Barcelona','BAR','Fácil'),('Raphinha','EI','Brasil','🇧🇷','FC Barcelona','BAR','Fácil'),('Pedri','MC','España','🇪🇸','FC Barcelona','BAR','Fácil'),('Frenkie de Jong','MC','Países Bajos','🇳🇱','FC Barcelona','BAR','Media'),('Dani Olmo','MCO','España','🇪🇸','FC Barcelona','BAR','Media'),('Jules Koundé','LD','Francia','🇫🇷','FC Barcelona','BAR','Difícil'),('Pau Cubarsí','DFC','España','🇪🇸','FC Barcelona','BAR','Difícil'),('Alejandro Balde','LI','España','🇪🇸','FC Barcelona','BAR','Media'),('Kylian Mbappé','DC','Francia','🇫🇷','Real Madrid','RMA','Fácil'),('Vinícius Júnior','EI','Brasil','🇧🇷','Real Madrid','RMA','Fácil'),('Jude Bellingham','MC','Inglaterra','🏴','Real Madrid','RMA','Fácil'),('Federico Valverde','MC','Uruguay','🇺🇾','Real Madrid','RMA','Media'),('Eduardo Camavinga','MCD','Francia','🇫🇷','Real Madrid','RMA','Media'),('Aurélien Tchouaméni','MCD','Francia','🇫🇷','Real Madrid','RMA','Difícil'),('Arda Güler','MCO','Turquía','🇹🇷','Real Madrid','RMA','Difícil'),('Rodrygo','ED','Brasil','🇧🇷','Real Madrid','RMA','Media'),('Antoine Griezmann','MCO','Francia','🇫🇷','Atlético de Madrid','ATM','Fácil'),('Julián Álvarez','DC','Argentina','🇦🇷','Atlético de Madrid','ATM','Fácil'),('Pablo Barrios','MC','España','🇪🇸','Atlético de Madrid','ATM','Experto'),('Nico Williams','EI','España','🇪🇸','Athletic Club','ATH','Fácil'),('Oihan Sancet','MCO','España','🇪🇸','Athletic Club','ATH','Difícil'),('Mikel Oyarzabal','EI','España','🇪🇸','Real Sociedad','RSO','Media'),('Takefusa Kubo','ED','Japón','🇯🇵','Real Sociedad','RSO','Media'),('Isco','MCO','España','🇪🇸','Real Betis','BET','Fácil'),('Ayoze Pérez','DC','España','🇪🇸','Villarreal','VIL','Difícil'),
# Premier
('Bukayo Saka','ED','Inglaterra','🏴','Arsenal','ARS','Fácil'),('Martin Ødegaard','MCO','Noruega','🇳🇴','Arsenal','ARS','Fácil'),('Declan Rice','MCD','Inglaterra','🏴','Arsenal','ARS','Fácil'),('William Saliba','DFC','Francia','🇫🇷','Arsenal','ARS','Media'),('Kai Havertz','DC','Alemania','🇩🇪','Arsenal','ARS','Media'),('Gabriel Martinelli','EI','Brasil','🇧🇷','Arsenal','ARS','Media'),('Mohamed Salah','ED','Egipto','🇪🇬','Liverpool','LIV','Fácil'),('Florian Wirtz','MCO','Alemania','🇩🇪','Liverpool','LIV','Fácil'),('Alexander Isak','DC','Suecia','🇸🇪','Liverpool','LIV','Fácil'),('Alexis Mac Allister','MC','Argentina','🇦🇷','Liverpool','LIV','Media'),('Dominik Szoboszlai','MC','Hungría','🇭🇺','Liverpool','LIV','Media'),('Cody Gakpo','EI','Países Bajos','🇳🇱','Liverpool','LIV','Media'),('Virgil van Dijk','DFC','Países Bajos','🇳🇱','Liverpool','LIV','Fácil'),('Erling Haaland','DC','Noruega','🇳🇴','Manchester City','MCI','Fácil'),('Phil Foden','ED','Inglaterra','🏴','Manchester City','MCI','Fácil'),('Rodri','MCD','España','🇪🇸','Manchester City','MCI','Fácil'),('Bernardo Silva','MC','Portugal','🇵🇹','Manchester City','MCI','Media'),('Rúben Dias','DFC','Portugal','🇵🇹','Manchester City','MCI','Media'),('Kevin De Bruyne','MCO','Bélgica','🇧🇪','Manchester City','MCI','Fácil'),('Bruno Fernandes','MCO','Portugal','🇵🇹','Manchester United','MUN','Fácil'),('Kobbie Mainoo','MC','Inglaterra','🏴','Manchester United','MUN','Difícil'),('Cole Palmer','MCO','Inglaterra','🏴','Chelsea','CHE','Fácil'),('Enzo Fernández','MC','Argentina','🇦🇷','Chelsea','CHE','Media'),('Moisés Caicedo','MCD','Ecuador','🇪🇨','Chelsea','CHE','Media'),('Son Heung-min','EI','Corea del Sur','🇰🇷','Tottenham','TOT','Fácil'),
# Bundesliga
('Harry Kane','DC','Inglaterra','🏴','Bayern Múnich','BAY','Fácil'),('Jamal Musiala','MCO','Alemania','🇩🇪','Bayern Múnich','BAY','Fácil'),('Joshua Kimmich','MCD','Alemania','🇩🇪','Bayern Múnich','BAY','Fácil'),('Michael Olise','ED','Francia','🇫🇷','Bayern Múnich','BAY','Media'),('Alphonso Davies','LI','Canadá','🇨🇦','Bayern Múnich','BAY','Media'),('Jonathan Tah','DFC','Alemania','🇩🇪','Bayern Múnich','BAY','Difícil'),('Serge Gnabry','ED','Alemania','🇩🇪','Bayern Múnich','BAY','Media'),('Gregor Kobel','POR','Suiza','🇨🇭','Borussia Dortmund','BVB','Difícil'),('Jobe Bellingham','MC','Inglaterra','🏴','Borussia Dortmund','BVB','Difícil'),('Nico Schlotterbeck','DFC','Alemania','🇩🇪','Borussia Dortmund','BVB','Media'),('Serhou Guirassy','DC','Guinea','🇬🇳','Borussia Dortmund','BVB','Difícil'),('Emre Can','MCD','Alemania','🇩🇪','Borussia Dortmund','BVB','Media'),('Florian Neuhaus','MC','Alemania','🇩🇪','Borussia Mönchengladbach','BMG','Experto'),('Xavi Simons','MCO','Países Bajos','🇳🇱','RB Leipzig','RBL','Media'),('Benjamin Šeško','DC','Eslovenia','🇸🇮','RB Leipzig','RBL','Media'),('Loïs Openda','DC','Bélgica','🇧🇪','RB Leipzig','RBL','Difícil'),('Alejandro Grimaldo','LI','España','🇪🇸','Bayer Leverkusen','LEV','Media'),('Florian Wirtz','MCO','Alemania','🇩🇪','Bayer Leverkusen','LEV','Fácil'),('Jeremie Frimpong','LD','Países Bajos','🇳🇱','Bayer Leverkusen','LEV','Media'),('Granit Xhaka','MCD','Suiza','🇨🇭','Bayer Leverkusen','LEV','Media'),
# Serie A
('Lautaro Martínez','DC','Argentina','🇦🇷','Inter','INT','Fácil'),('Nicolò Barella','MC','Italia','🇮🇹','Inter','INT','Media'),('Alessandro Bastoni','DFC','Italia','🇮🇹','Inter','INT','Media'),('Federico Dimarco','LI','Italia','🇮🇹','Inter','INT','Media'),('Hakan Çalhanoğlu','MCD','Turquía','🇹🇷','Inter','INT','Difícil'),('Marcus Thuram','DC','Francia','🇫🇷','Inter','INT','Fácil'),('Rafael Leão','EI','Portugal','🇵🇹','AC Milan','MIL','Fácil'),('Christian Pulisic','ED','Estados Unidos','🇺🇸','AC Milan','MIL','Fácil'),('Tijjani Reijnders','MC','Países Bajos','🇳🇱','AC Milan','MIL','Difícil'),('Theo Hernández','LI','Francia','🇫🇷','AC Milan','MIL','Fácil'),('Dušan Vlahović','DC','Serbia','🇷🇸','Juventus','JUV','Media'),('Kenan Yıldız','MCO','Turquía','🇹🇷','Juventus','JUV','Difícil'),('Teun Koopmeiners','MC','Países Bajos','🇳🇱','Juventus','JUV','Difícil'),('Federico Chiesa','EI','Italia','🇮🇹','Liverpool','LIV','Media'),('Paulo Dybala','MCO','Argentina','🇦🇷','Roma','ROM','Fácil'),('Mats Hummels','DFC','Alemania','🇩🇪','Roma','ROM','Difícil'),('Artem Dovbyk','DC','Ucrania','🇺🇦','Roma','ROM','Difícil'),('Khvicha Kvaratskhelia','EI','Georgia','🇬🇪','Napoli','NAP','Fácil'),('Romelu Lukaku','DC','Bélgica','🇧🇪','Napoli','NAP','Fácil'),('Scott McTominay','MC','Escocia','🏴','Napoli','NAP','Media'),('Rasmus Højlund','DC','Dinamarca','🇩🇰','Napoli','NAP','Media'),
# Ligue 1 / other Europe
('Ousmane Dembélé','ED','Francia','🇫🇷','Paris Saint-Germain','PSG','Fácil'),('Achraf Hakimi','LD','Marruecos','🇲🇦','Paris Saint-Germain','PSG','Fácil'),('Marquinhos','DFC','Brasil','🇧🇷','Paris Saint-Germain','PSG','Fácil'),('Vitinha','MC','Portugal','🇵🇹','Paris Saint-Germain','PSG','Media'),('Warren Zaïre-Emery','MC','Francia','🇫🇷','Paris Saint-Germain','PSG','Difícil'),('Khvicha Kvaratskhelia','EI','Georgia','🇬🇪','Paris Saint-Germain','PSG','Media'),('Bradley Barcola','EI','Francia','🇫🇷','Paris Saint-Germain','PSG','Media'),('Rayan Cherki','MCO','Francia','🇫🇷','Manchester City','MCI','Difícil'),('Jonathan David','DC','Canadá','🇨🇦','Juventus','JUV','Media'),('Nuno Mendes','LI','Portugal','🇵🇹','Paris Saint-Germain','PSG','Media'),
# Portugal / Netherlands / Saudi / MLS
('Bruno Fernandes','MCO','Portugal','🇵🇹','Manchester United','MUN','Fácil'),('Viktor Gyökeres','DC','Suecia','🇸🇪','Arsenal','ARS','Fácil'),('Trincão','ED','Portugal','🇵🇹','Sporting CP','SCP','Difícil'),('Pedro Gonçalves','MCO','Portugal','🇵🇹','Sporting CP','SCP','Difícil'),('Ángel Di María','ED','Argentina','🇦🇷','Rosario Central','ROS','Media'),('António Silva','DFC','Portugal','🇵🇹','Benfica','BEN','Difícil'),('João Neves','MC','Portugal','🇵🇹','Paris Saint-Germain','PSG','Media'),('Frenkie de Jong','MC','Países Bajos','🇳🇱','FC Barcelona','BAR','Media'),('Virgil van Dijk','DFC','Países Bajos','🇳🇱','Liverpool','LIV','Fácil'),('Dusan Tadic','MCO','Serbia','🇷🇸','Fenerbahçe','FEN','Experto'),('Cristiano Ronaldo','DC','Portugal','🇵🇹','Al-Nassr','NAS','Fácil'),('Sadio Mané','EI','Senegal','🇸🇳','Al-Nassr','NAS','Media'),('Riyad Mahrez','ED','Argelia','🇩🇿','Al-Ahli','AHL','Media'),('Neymar','EI','Brasil','🇧🇷','Santos','SAN','Fácil'),('Lionel Messi','ED','Argentina','🇦🇷','Inter Miami','MIA','Fácil'),('Luis Suárez','DC','Uruguay','🇺🇾','Inter Miami','MIA','Media'),('Sergio Busquets','MCD','España','🇪🇸','Inter Miami','MIA','Difícil'),('Jordi Alba','LI','España','🇪🇸','Inter Miami','MIA','Media'),
]
for r in rows: add(*r)
# Promote a group of less obvious names to expert difficulty
expert_names={'Pablo Barrios','Oihan Sancet','Jonathan Tah','Jobe Bellingham','Gregor Kobel','Florian Neuhaus','António Silva','Dusan Tadic','Sergio Busquets','Trincão','Pedro Gonçalves','Tijjani Reijnders','Teun Koopmeiners','Hakan Çalhanoğlu'}
for p in players:
    if p['name'] in expert_names: p['difficulty']='Experto'
# remove duplicate exact names, keeping first occurrence
seen=set(); unique=[]
for p in players:
    if p['name'] not in seen:
        seen.add(p['name']); unique.append(p)
players=unique
# Ensure at least 100 and distribute enough in each tier
print('players',len(players), {d:sum(p['difficulty']==d for p in players) for d in ['Fácil','Media','Difícil','Experto']})
# write JSON-ish JS data
with open('/mnt/data/v3/juego-pesca/players.js','w',encoding='utf8') as f:
    f.write('const PLAYER_DATABASE = ' + json.dumps(players, ensure_ascii=False, indent=2) + ';\n')
